### ISSUE TITLE
can you explain it?

### ISSUE THREAD

**Issue by shenlei190810** [kaltura/nginx-srt-module#1]
as the code shows, when srt_post_flags==1, the sc struct is not put in the ngx_srt_srt_posted; I ask for the reason, thank you.
```
static void
ngx_srt_conn_post_srt(ngx_srt_conn_t *sc, uint32_t flags)
{
    ngx_flag_t  notify;

    ngx_log_debug2(NGX_LOG_DEBUG_EVENT, sc->connection->log, 0,
        "ngx_srt_conn_post_srt: conn: %p, flags: 0x%uxD", sc, flags);

    ngx_spinlock(&ngx_srt_srt_posted_lock, 1, 2048);

    if (!sc->srt_post_flags) {
        sc->srt_next = ngx_srt_srt_posted;
        ngx_srt_srt_posted = sc;

        notify = 1;
    } else {
        notify = 0;
    }

    sc->srt_post_flags |= flags;

    ngx_memory_barrier();

    ngx_unlock(&ngx_srt_srt_posted_lock);

    if (notify) {
        (void) ngx_srt_epoll_notify(sc->connection->log);
    }
}
```
![1](https://user-images.githubusercontent.com/3354569/150665004-a3aa5a54-2e03-4dec-84e6-f43d27e92287.png)

**Comment by kaltura-hooks** [comment]
Hi @shenlei190810,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment]
These functions are used for passing notifications between the SRT thread and the main nginx thread. There is a linked list of pending connections for each thread, events are sent by adding the connection object to the list + writing to an eventfd. If the post flags are non-zero (note that it's not necessarily 1, can be any mix of NGX_SRT_POST_XXX flags), it means the connection object is already linked to the respective list, so it should not be added again.
