### ISSUE TITLE
srt ingest adaptive bitrate hls out

### ISSUE THREAD

**Issue by kevev** [kaltura/nginx-srt-module#17]
Great module! Is it possible to ingest srt and output adaptive bitrate hls chunks?

If so, do you have a solid nginx config as an example? Thank You!

**Comment by erankor** [comment]
This module deals with the "transport layer" - it only converts SRT -> TCP.
To convert the mpegts which is transferred inside the SRT to HLS, you'll need another module. We haven't yet open sourced this component, but hopefully we will get to it soon...
Our solution is based on a modified version of https://github.com/arut/nginx-ts-module, you can try your luck with that module. Although IIRC the "stream" (TCP) implementation there is incomplete - it won't even compile because of a typo here - https://github.com/arut/nginx-ts-module/blob/master/src/ngx_stream_ts_module.c#L143...

**Comment by kevev** [comment]
Thank You for the reply. I will wait for your component release.

**Comment by kevev** [comment]
I was able to figure this out. Seems very stable.
ffmpeg with SRT support built in mode=listener -->nginx-rtmp-module --> hls abr using ffmpeg.
